api_version: 1
threadsafe: true
runtime: python27

handlers:
- url: /\.well\-known\/acme\-challenge\/.*
  script: letsencrypt.app

- url: /tfxkl17/bower_components
  static_dir: tfxkl17/build/tfxkl17/bower_components

- url: /tfxkl17/data
  static_dir: tfxkl17/build/tfxkl17/data

- url: /tfxkl17/images
  static_dir: tfxkl17/build/tfxkl17/images

- url: /tfxkl17/src
  static_dir: tfxkl17/build/tfxkl17/src

- url: /tfxkl17/manifest.json
  static_files: tfxkl17/build/tfxkl17/manifest.json
  upload: tfxkl17/build/tfxkl17/manifest.json
  
- url: /tfxkl17/.*
  static_files: tfxkl17/build/tfxkl17/index.html
  upload: tfxkl17/build/tfxkl17/index.html

- url: /tfxkl17.*
  script: main.app

- url: /.*
  script: main.app

skip_files:
  - tfxkl17/bower_components
  - tfxkl17/src
  - tfxkl17/data
  - tfxkl17/images